<?php
  session_start();

  // Include the helpers file for utility functions. This file contains common functions that can be used throughout the application.
  require '../helpers.php';


  /* 
  * Load the Composer autoload file.
  * This file is generated by Composer and follows the PSR-4 autoloading standard, 
  * allowing you to automatically load classes from the 'vendor' directory based on their namespaces.
  */ 
  require __DIR__ . '/../vendor/autoload.php';


  // Register a function with the PHP autoloader to automatically load class files when they are needed.
  // spl_autoload_register(function ($class){

  //   // Construct the file path to the class file within the 'Framework' directory. The class name is appended to the path with a '.php' extension.
  //   $path = basePath('Framework/' . $class . '.php');

  //   // Check if the constructed file path exists. If the file exists, require it to include the class definition in the script.
  //   if(file_exists($path)){
  //     require $path;
  //   }

  // });


  // Import the Router class from the Framework namespace. This allows you to use the Router class in this file without needing to specify the full namespace each time.
  use Framework\Router;


  // Create a new instance of the Router class. The Router class is responsible for managing and routing HTTP requests to the appropriate controllers.
  $router = new Router();

  // Load the routes configuration from the routes.php file. This file contains the route definitions that map URLs to specific controllers.
  $routes = require basePath('routes.php');

  // Parse the current URI from the server's REQUEST_URI variable, extracting only the path component. This ensures that only the path (e.g., "/home" instead of "/home?query=string") is used for routing.
  $uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
  // Uncomment the following line to debug the URI by inspecting and stopping the script.
  // inspectAndDie($uri);

  // Route the request based on the URI and method. The router matches the URI and method to the defined routes and loads the corresponding controller.
  $router->route($uri);

?>